ipa320/setup_cob4

upstart_msh/cob-start
upstart_msh/cob-stop
upstart_msh/upstart_install.sh

This PR partly solves https://github.com/ipa320/msh/issues/628

Startup roscore and bringup inside tmux sessions

---

InstallCob4.sh

this solves https://github.com/ipa320/msh/issues/616

update install scirpt ot install NoMachine!

---

scripts/cob-shutdown

get the active pcs from nmap command

optimice cob-shutdown

---

InstallCob4.sh
scripts/livehost.sh
scripts/sync_packages.sh
upstart/upstart_install.sh

solves merge conflict #69 and add some updates

Optimice installation 2.0

---

scripts/sync_packages.sh

fix #81 
for some reason https://github.com/ipa320/setup_cob4/commit/414da57e2d3a976f62bc0827daee984595eebcdc introduced changes which broke the sync script, i.e. the packages list was empty for sensorring
this PR now reverts these change and was tested on `cob4-7`

fix sync_packages

---

InstallCob4.sh

An error during a merge deleted the setup of the working version of NTP...

Revert ntp configuration

---

cob-pcs/cob-pcs-execute.sh
cob-pcs/cob-pcs-install.sh

as suggested by @ipa-nhg in https://github.com/ipa320/setup_cob4/pull/105/files/f445f0eafbc80e1cdff4bafae22d9f11a6ff5364#r125216774 (left over from #105)

use ip instead of hostnames

---

cob-pcs/cob-pcs-execute.sh
cob-pcs/cob-pcs-install.sh

fix for composition of client_list in cob_pc scripts

---

cob-pcs/cob-pcs-execute.sh
cob-pcs/cob-pcs-install.sh
cob-pcs/sync_packages.sh
scripts/cob-command
scripts/cob-shutdown

needed for robots with grippers. If we don't change the range we will have to create all the users also for the grippers (make not sense)

update the IP range

---

PostInstallCob4.sh
upstart/cob-start

This PR substitute the https://github.com/ipa320/setup_cob4/pull/130 and https://github.com/ipa320/setup_cob4/pull/107
Includes also the mimic setup and upstart installation. Once is merged setup_cob4 repository can be cleaned

[WIP] Updated version of post installation script

---

PostInstallCob4.sh
cob-adduser
cob-pcs/user.bashrc
scripts/cob-command

- fixes issues left from https://github.com/ipa320/setup_cob4/pull/147 and https://github.com/ipa320/setup_cob4/pull/140
- fixes https://github.com/ipa320/setup_cob4/issues/149
- improved readability of code
- reduces duplicate code (IntsallUpstart vs UpdateUpstart)
- improuvs usability of Postinstall script for upstart installation

fix post install script with upstart

---

PostInstallCob4.sh

disable root openssh popup authetification

---

images_config/ks-robot-master.cfg
images_config/ks-robot-slave.cfg

DO NOT MERGE: still needs to be tested on a master and slave installation

beautify image installation

---

cob-pcs/tmux.conf

as suggested in https://github.com/ipa320/setup_cob4/issues/142
this is already tested.
I think we should start with this config rather than using all (untested) configs from https://github.com/ipa320/setup_cob4/pull/176

extend tmux history

---

images_config/ks-robot-master.cfg
images_config/ks-robot-slave.cfg

also contributes to #170 
@ipa-fmw @ipa-nhg @ipa-bnm 
is this the correct spot to add additional packages? do I need to add something anywhere else?

additional packages

---

manual_administrator/README_ddwrt.md

fixes https://github.com/ipa320/msh/issues/869

Howto to disable direct wifi

---

images_config/ks-robot-master.cfg
images_config/ks-robot-slave.cfg

fixes https://github.com/ipa320/setup_cob4/issues/154

increase version number for nomachine

---

upstart/cob-start

fixes https://github.com/ipa320/msh/issues/887

fix auto login

---

images_config/ks-robot-master.cfg
images_config/ks-robot-slave.cfg

related to https://github.com/ipa320/msh/issues/872
post-step for image setup
:warning: needs to be tested :warning:

post step to disable lts update popup

---

PostInstallCob4.sh
upstart/hdg_cob_robots.yaml
upstart/hdg_unity_robots.yaml

add upstart config files for hdg

---

cob-pcs/analyze_packages.sh
cob-pcs/sync_packages.sh

@HannesBachter please test on `cob4-24`

backport sync_packages

---

.gitignore
PostInstallCob4.sh
cob-pcs/analyze_packages.sh
cob-pcs/cob-pcs-install.sh
cob-pcs/sync_packages.sh

@HannesBachter please test this branch when setting up research robot cob4-8 for Aalto

backport latest mojin updates

---

PostInstallCob4.sh
cob-adduser
images_config/kickstart/kickstart-robot.sh
scripts/cob-powerbutton
scripts/robmuxinator

fixup backport mojin updates
